CREATE TABLE DEPT
(
    DNO NUMBER PRIMARY KEY,
    DNAME VARCHAR2(30) NOT NULL
);

INSERT INTO DEPT VALUES (10, 'CSE');
INSERT INTO DEPT VALUES (20, 'ME');
INSERT INTO DEPT VALUES (30, 'CE');
INSERT INTO DEPT VALUES (40, 'EEE');
INSERT INTO DEPT VALUES (50, 'ECE');
INSERT INTO DEPT VALUES (60, 'CSM');
INSERT INTO DEPT VALUES (70, 'CSD');

COMMIT;

CREATE TABLE STUDENT
(
    SID NUMBER PRIMARY KEY,
    SNAME VARCHAR2(30) NOT NULL,
    DID NUMBER,
    CONSTRAINT FK_STUDENT_DEPT
        FOREIGN KEY (DID) REFERENCES DEPT(DNO)
);

INSERT INTO STUDENT VALUES (101, 'Rahul', 10);
INSERT INTO STUDENT VALUES (102, 'Sneha', 20);
INSERT INTO STUDENT VALUES (103, 'Arjun', 30);
INSERT INTO STUDENT VALUES (104, 'Kiran', 40);
INSERT INTO STUDENT VALUES (105, 'Priya', 50);
INSERT INTO STUDENT VALUES (106, 'Nikhil', 60);
INSERT INTO STUDENT VALUES (107, 'Anjali', 10);
INSERT INTO STUDENT VALUES (108, 'Ravi', 20);
INSERT INTO STUDENT VALUES (109, 'Divya', 30);
INSERT INTO STUDENT VALUES (110, 'Vijay', 40);

COMMIT;

SELECT S.SID, S.SNAME, D.DNO, D.DNAME
FROM STUDENT S
JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID,
       S.SNAME,
       D.DNAME
FROM STUDENT S
JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID,
       S.SNAME,
       S.DID,
       D.DNAME
FROM STUDENT S, DEPT D
WHERE S.DID > D.DNO;

LEFT OUTER NATURAL JOIN
SELECT S.SID,
       S.SNAME,
       D.DNAME
FROM STUDENT S
LEFT OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID,
       S.SNAME,
       D.DNAME
FROM STUDENT S
RIGHT OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID,
       S.SNAME,
       D.DNAME
FROM STUDENT S
FULL OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID,
       S.SNAME,
       D.DNAME
FROM STUDENT S
LEFT OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID,
       S.SNAME,
       D.DNAME
FROM STUDENT S
RIGHT OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID,
       S.SNAME,
       D.DNAME
FROM STUDENT S
FULL OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID,
       S.SNAME,
       S.DID,
       D.DNO,
       D.DNAME
FROM STUDENT S
LEFT OUTER JOIN DEPT D
ON S.DID > D.DNO;

SELECT S.SID,
       S.SNAME,
       S.DID,
       D.DNO,
       D.DNAME
FROM STUDENT S
RIGHT OUTER JOIN DEPT D
ON S.DID > D.DNO;

SELECT S.SID,
       S.SNAME,
       S.DID,
       D.DNO,
       D.DNAME
FROM STUDENT S
FULL OUTER JOIN DEPT D
ON S.DID > D.DNO;

SELECT S.SID,
       S.SNAME,
       D.DNO,
       D.DNAME
FROM STUDENT S
CROSS JOIN DEPT D;

SELECT S.SID,
       S.SNAME,
       S.DID,
       D.DNO,
       D.DNAME
FROM STUDENT S
FULL OUTER JOIN DEPT D
ON S.DID > D.DNO;

SELECT S.SID,
       S.SNAME,
       D.DNO,
       D.DNAME
FROM STUDENT S
CROSS JOIN DEPT D;